"use client";

import React, { useEffect, useState } from "react";

export default function InterviewReportPage() {
  const [loading, setLoading] = useState(true);
  const [responses, setResponses] = useState([]);

  useEffect(() => {
    const data = JSON.parse(localStorage.getItem("interviewResults") || "[]");
    setResponses(data);
    setLoading(false);
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center text-white text-xl">
        Loading Report...
      </div>
    );
  }

  const technicalAvg = Math.round(
    responses.reduce((acc, r) => acc + r.technicalScore, 0) / responses.length
  );

  const communicationAvg = Math.round(
    responses.reduce((acc, r) => acc + r.communicationScore, 0) / responses.length
  );

  return (
    <div className="min-h-screen pt-24 p-8 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-white">
      <div className="max-w-5xl mx-auto space-y-10">

        {/* Header Section */}
        <div className="text-center space-y-3">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-sky-400 via-indigo-400 to-purple-400 bg-clip-text text-transparent">
            AI Interview Report
          </h1>
          <p className="text-slate-300">
            Automatically generated by DevHire's AI after analyzing all your answers.
          </p>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Technical Score */}
          <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-700/50 backdrop-blur-xl shadow-lg">
            <h2 className="text-lg font-semibold text-sky-300">Technical Score</h2>
            <p className="text-5xl font-bold mt-2 bg-gradient-to-r from-sky-400 to-indigo-400 text-transparent bg-clip-text">
              {technicalAvg}/10
            </p>
            <p className="text-slate-400 text-sm mt-2">
              Based on correctness, completeness & depth of answers.
            </p>
          </div>

          {/* Communication Score */}
          <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-700/50 backdrop-blur-xl shadow-lg">
            <h2 className="text-lg font-semibold text-purple-300">Communication Score</h2>
            <p className="text-5xl font-bold mt-2 bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
              {communicationAvg}/10
            </p>
            <p className="text-slate-400 text-sm mt-2">
              Based on clarity, structure, grammar & delivery.
            </p>
          </div>
        </div>

        {/* Grammar Issues */}
        <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-700/50 backdrop-blur-xl">
          <h2 className="text-xl font-semibold text-sky-300 mb-4">Common Grammar Issues</h2>

          {responses.every((r) => r.grammarIssues.length === 0) ? (
            <p className="text-slate-400">No major grammar issues detected. Great job!</p>
          ) : (
            <ul className="list-disc ml-6 space-y-2 text-slate-300">
              {responses.flatMap((r) => r.grammarIssues).map((g, i) => (
                <li key={i}>{g}</li>
              ))}
            </ul>
          )}
        </div>

        {/* Filler Words */}
        <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-700/50 backdrop-blur-xl">
          <h2 className="text-xl font-semibold text-purple-300 mb-4">Filler Words Detected</h2>

          {responses.every((r) => r.fillerWords.length === 0) ? (
            <p className="text-slate-400">You avoided filler words. Nice speaking clarity!</p>
          ) : (
            <ul className="list-disc ml-6 space-y-2 text-slate-300">
              {responses.flatMap((r) => r.fillerWords).map((w, i) => (
                <li key={i}>{w}</li>
              ))}
            </ul>
          )}
        </div>

        {/* Detailed Breakdown */}
        <div className="space-y-6">
          <h2 className="text-2xl font-bold bg-gradient-to-r from-sky-400 to-indigo-400 bg-clip-text text-transparent">
            Question-by-Question Breakdown
          </h2>

          {responses.map((res, i) => (
            <div
              key={i}
              className="p-6 rounded-2xl bg-black/40 border border-slate-800 backdrop-blur-xl space-y-3"
            >
              <h3 className="text-lg font-semibold text-sky-300">Question {i + 1}</h3>

              <p className="text-slate-300">
                <span className="font-medium text-white">Correctness:</span>{" "}
                {res.correctness}
              </p>

              <p className="text-slate-300">
                <span className="font-medium text-white">Missing points:</span>{" "}
                {res.missingPoints || "None"}
              </p>

              <p className="text-slate-300">
                <span className="font-medium text-white">Improvement:</span>{" "}
                {res.improvement || "Good attempt!"}
              </p>
            </div>
          ))}
        </div>

        {/* Finish Button */}
        <div className="text-center mt-12">
          <button
            onClick={() => (window.location.href = "/dashboard/student/interviews")}
            className="px-6 py-3 rounded-xl bg-gradient-to-r from-sky-500 via-indigo-500 to-purple-500 text-slate-950 font-semibold shadow-lg hover:scale-105 transition"
          >
            Back to Interviews
          </button>
        </div>
      </div>
    </div>
  );
}
